latest changes

diff --git a/install b/install
--- a/install
+++ b/install
@@ -55,22 +55,21 @@ echo -n
 echo -n "Installing Bitwarden dependencies..."
 echo "$passwd" | sudo -S zypper --non-interactive install libnotify-tools
 
-BWURL=$(curl -s https://api.github.com/repos/bitwarden/clients/releases | jq -r 'first(.[] | .assets[]? | select(.browser_download_url | endswith(".rpm")) | .browser_download_url)')
-
-if [ -n "$BWURL" ]; then
-    echo "Downloading Bitwarden from $BWURL"
-    curl -L -o "{$datadir}bitwarden-latest.rpm" "$BWURL" 
-else
-    echo "--- Could not find Bitwarden RPM URL"
-    exit 1
-fi
-
-if test -f "{$datadir}bitwarden-latest.rpm"; then
-    echo "$passwd" | sudo -S rpm -i bitwarden-latest.rpm
-fi
-
-rm "{$datadir}bitwarden-latest.rpm"
-
+# BWURL=$(curl -s https://api.github.com/repos/bitwarden/clients/releases | jq -r 'first(.[] | .assets[]? | select(.browser_download_url | endswith(".rpm")) | .browser_download_url)')
+# 
+# if [ -n "$BWURL" ]; then
+#     echo "Downloading Bitwarden from $BWURL"
+#     curl -L -o "{$datadir}bitwarden-latest.rpm" "$BWURL" 
+# else
+#     echo "--- Could not find Bitwarden RPM URL"
+#     exit 1
+# fi
+# 
+# if test -f "{$datadir}bitwarden-latest.rpm"; then
+#     echo "$passwd" | sudo -S rpm -i bitwarden-latest.rpm
+# fi
+# 
+# rm "{$datadir}bitwarden-latest.rpm"
 
 # shellcheck disable=SC2129
 echo >> "$shrc"
