installation is now transactional

diff --git a/install b/install
--- a/install
+++ b/install
@@ -66,6 +66,33 @@ else
     exit 1
 fi
 
+if [[ -L "$shrc" ]]; then
+    if [[ ! -e "$shrc" ]]; then
+        echo "Cannot update $shrc: it is a broken symbolic link." >&2
+        exit 1
+    fi
+    shrc_target=$(realpath "$shrc")
+else
+    shrc_target="$shrc"
+fi
+
+shrc_tmp=$(mktemp "${shrc_target}.sherry.XXXXXX")
+cleanup() {
+    if [[ -n ${shrc_tmp:-} ]]; then
+        rm -f -- "$shrc_tmp"
+    fi
+}
+trap cleanup EXIT
+
+if [[ -e "$shrc" ]]; then
+    cp --preserve=mode -- "$shrc" "$shrc_tmp"
+fi
+
+if grep -Eq '^# (begin sherry([[:space:]]|$)|end sherry$)' "$shrc_tmp"; then
+    echo "Sherry configuration already exists in $shrc; no changes were made." >&2
+    exit 1
+fi
+
 # install necessary packages
 echo -n
 echo -n "Please enter your password to install packages via zypper: "
@@ -82,36 +109,37 @@ echo -n
 echo -n "Installing Bitwarden dependencies..."
 echo "$passwd" | sudo -S zypper --non-interactive install libnotify-tools
 
-# BWURL=$(curl -s https://api.github.com/repos/bitwarden/clients/releases | jq -r 'first(.[] | .assets[]? | select(.browser_download_url | endswith(".rpm")) | .browser_download_url)')
+# BWURL=$(curl -fsSL https://api.github.com/repos/bitwarden/clients/releases | jq -r 'first(.[] | .assets[]? | select(.browser_download_url | endswith(".rpm")) | .browser_download_url)')
 # 
 # if [ -n "$BWURL" ]; then
 #     echo "Downloading Bitwarden from $BWURL"
-#     curl -L -o "{$datadir}bitwarden-latest.rpm" "$BWURL" 
+#     curl -L -o "${datadir}bitwarden-latest.rpm" "$BWURL" 
 # else
 #     echo "--- Could not find Bitwarden RPM URL"
 #     exit 1
 # fi
 # 
-# if test -f "{$datadir}bitwarden-latest.rpm"; then
-#     echo "$passwd" | sudo -S rpm -i bitwarden-latest.rpm
+# if test -f "${datadir}bitwarden-latest.rpm"; then
+#     echo "$passwd" | sudo -S rpm -i ${datadir}bitwarden-latest.rpm
 # fi
 # 
-# rm "{$datadir}bitwarden-latest.rpm"
+# rm "${datadir}bitwarden-latest.rpm"
 
 # shellcheck disable=SC2129
-echo >> "$shrc"
-echo "# begin sherry (the following lines have been automatically added by sherry)" >> "$shrc"
-echo >> "$shrc"
+echo >> "$shrc_tmp"
+echo "# begin sherry (the following lines have been automatically added by sherry)" >> "$shrc_tmp"
+echo >> "$shrc_tmp"
 
 # fzf
 if [ ! -d "$HOME/.fzf" ]; then
     echo ' * Installing FZF...'
     echo
     git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
-    ~/.fzf/install
+    ~/.fzf/install --key-bindings --completion --no-update-rc
 else 
     echo ' * FZF already installed.'
 fi
+echo '[ -f ~/.fzf.bash ] && source ~/.fzf.bash' >> "$shrc_tmp"
 
 # configure case-insensitive autocompletion
 if [ ! -f "$HOME/.inputrc" ]; then
@@ -127,7 +155,7 @@ fi
 echo ' * Adding shell files to .bashrc...'
 for file in "$datadir"shell/*.sh; do
     echo "   * Sourcing $file"
-    echo "source $( realpath "$file" )" >> "$shrc"
+    echo "source $( realpath "$file" )" >> "$shrc_tmp"
 done
 echo
 
@@ -171,9 +199,17 @@ done
 
 # finish setting up zoxide
 # shellcheck disable=SC2016,SC2129
-echo 'eval "$(zoxide init bash)"' >> "$shrc"
+echo 'eval "$(zoxide init bash)"' >> "$shrc_tmp"
 
 # shellcheck disable=SC2129
-echo >> "$shrc"
-echo "# end sherry" >> "$shrc"
-echo >> "$shrc"
+echo >> "$shrc_tmp"
+echo "# end sherry" >> "$shrc_tmp"
+echo >> "$shrc_tmp"
+
+if ! bash -n "$shrc_tmp"; then
+    echo "The staged Bash configuration is invalid; $shrc was not changed." >&2
+    exit 1
+fi
+
+mv -- "$shrc_tmp" "$shrc_target"
+shrc_tmp=''
